var employeeTags = {
	"Abe Danziger": ['customer success', 'arlo', 'skyline', 'big data', 'cloud computing', 'sales', 'strategy', 'enterprise', 'saas', 'hebrew'],
	//"Adam Balint": ['backend', 'back end', 'hungarian', 'machine learning', 'aml', 'intern', 'korean'],
	"Alex Cook": ['sales', 'basketball', 'clarifai', 'eating'],
	"Alex Freska": ['frontend', 'front end', 'search demo', 'react', 'javascript', 'php', 'html', 'python', 'mongodb', 'backbone', 'redux', 'jenkins', 'c++', 'web apps', 'running', 'biking'], 
	"Alison Klein": ['legal', 'law', 'litigation', 'corporate governance'],
	"Amanda Coyle": ['HR', 'onboarding', 'cetf', 'chess', 'payroll'],
	"Amy Kim": ['product', 'design', 'korean', 'search demo', 'running', 'mathematics', 'investment banking', 'entpreneurship'],
	"Arya Seghatoleslami": ['javascript', 'front end', 'frontend', 'ruby', 'node', 'react', 'jenkins', 'docker', 'blockchain', 'soccer', 'redux'],
	//"Ben Hayes": ['legal', 'litigation', 'legal writing', 'corporate law', 'intellectual property'],
	"Billy Lawler": [],
	"Blossom Coryat": ['hadoop', 'java', 'mongodb', 'javascript', 'sql', 'xml' ,'hackathons', 'perl', 'docker'],
	//"Brandon Clifton": ['accounting', 'dance', 'big data', 'snakes'],
	"Brian Novie": ['ios', 'c++', 'swift', 'unix', 'objective c', 'apple sdk', 'mobile sdk', 'sdk', 'xml', 'c', 'soap', 'subversion', 'distributed systems', 'scrum', 'cloud computing', 'shell scripting'],
	"Briana Gangi": ['it', 'video editing', 'javascript', 'html', 'it support', 'cats'],
	"Chenchao Zhao": ['physics', 'photography', 'data analysis', 'latex', 'machine learning', 'modeling', 'python', 'matlab', 'excel', 'fortran', 'photoshop', 'illustrator', 'chinese'],
	"Chris Moore": ['finance', 'billing', 'payments', 'stripe', 'suitesync', 'budgeting', 'basketball', 'baseball', 'football', 'weightlifting'],
	"Chul Gwon": ['govt', 'government', 'c++', 'scala', 'python', 'hadoop', 'c', 'java', 'linux', 'machine learning', 'latex', 'physics'],
	"Claire Geist": ['dst', 'photoshop', 'indesign', 'image editing', 'labeling', 'cats', 'instagram'],
	"Dalmo Cirne": ['mobile', 'sdk', 'python', 'mobile sdk', 'apple sdk', 'android sdk', 'c++', 'swift', 'ios', 'unix', 'linux', 'tensorflow', 'objective c', 'git', 'java', 'sql', 'mathematics', 'augmented reality', 'skiing'],
	"Daniel Owsley": ['infrastructure', 'ruby', 'docker', 'kubernetes', 'sql', 'javascript', 'ruby on rails', 'sql', 'bash', 'python', 'linux', 'git', 'node', 'mysql', 'cats'],
	"David Eigen": ['research', 'cnn', 'neural networks', 'machine learning'],
	"David Leonard": ['frontend', 'front end', 'search demo', 'c', 'django', 'jquery', 'javascript', 'css', 'sql', 'html', 'matlab', 'angular', 'node', 'react', 'swift', 'chess'],
	"David Kane": ['sales', 'hindi', 'powerpoint', 'salesforce'],
	"Dena Barnes": ['marketing', 'sales', 'salesforce', 'cold calling', 'football', 'baseball', 'basketball'],
	"Dianna Barry": ['backend', 'back end', 'c++', 'sql', 'python', 'html', 'linux', 'tensorflow', 'scala', 'c', 'java', 'postgres', 'unity', 'valgrind', 'glassblowing', 'ceramics', 'knitting'],
	"Edwin Renard": ['recruiting', 'talent', 'salesforce', 'hiring', 'cloud computing', 'staffing', 'digital marketing', 'marketing', 'sem', 'virtualization'],
	"Eric Loh": ['backend', 'back end', 'java', 'c'],
	"Elon Daniel": ['office management', 'cetf', 'music'],
	"Eran Nussinovitch": ['aml', 'java', 'python', 'c', 'c++', 'linux', 'cetf', 'machine learning', 'hebrew', 'chess'],
	"Eugenie Ma": ['recruiting', 'cetf', 'powerpoint', 'social media', 'event planning', 'public speaking'],
	"Glen You": ['government', 'sales', 'business development', 'salesforce', 'baseball'],
	"Grant Lightner": ['pmp', 'scrum', 'government', 'c++', 'perl', 'machine learning', 'project management', 'sem', 'agile','woodworking', 'auto repair', 'car repair', 'cars', 'handymanning'],
	"Habib Talavati": ['c++', 'pandas', 'postgres', 'sql', 'react', 'javascript', 'linux', 'docker', 'aws', 'nosql', 'java', 'backbone', 'latex', 'numpy', 'go', 'neural networks', 'machine learning'],
	"Haicheng Lin": ['graphic design', 'design', 'illustrator', 'photoshop', 'after effects', 'premiere', 'adobe', 'html', 'c#', 'lightroom', 'css', 'python', 'sketch', 'photography', 'ui/ux', 'marketing', 'cats', 'modeling', '3d modeling', '3d animation', 'animation', 'data visualization'],
	"Harmit Minhas": ['machine learning', 'backend', 'back end', 'weightlifting', 'mathematics', 'chess', 'go', 'python'],
	"Herbert Zheng": ['backend', 'back end', 'java', 'blockchain', 'c++', 'sql', 'python', 'financial modeling', 'machine learning', 'mba', 'chinese'],
	"Janvier Wijaya": ['java', 'subversion', 'php', 'objective c', 'jquery', 'xcode', 'python', 'swift', 'django', 'bootstrap', 'c++', 'c', 'javascript', 'opengl', 'sql', 'mysql', 'linux', 'mongodb', 'git'],
	"Jared Lerner": ['support', 'python', 'javascript', 'batch processing', 'help center', 'cetf', 'bash', 'sql', 'html', 'photoshop', 'gimp', 'postgres', 'powerpoint', 'postman', 'video editing', 'web design', 'creative writing', 'writing', 'drums', 'drumming', 'french', 'periscope', 'baseball', 'weightlifting', 'softball', 'football', 'cats'],
	"Jason Culler": ['design', 'front end', 'HTML', 'css', 'web design', 'graphic design', 'illustrator', 'photoshop', 'indesign', 'wireframing', 'sketch', 'branding', 'logo design', 'drawing'],
	"Jecky Tian": ['backend', 'back end', 'c++', 'python', 'php', 'postgres', 'sql', 'mysql', 'mongodb', 'javascript', 'linux'],
	//"Jeff Zhang": ['java', 'python', 'web scraping', 'linux', 'mongodb', 'git', 'javascript', 'mysql', 'linux', 'algorithms', 'redis', 'vim', 'go', 'shell scripting', 'chinese'],
	"Jesse Rappaport": ['python', 'php', 'css', 'laravel', 'bootstrap', 'mysql', 'sql', 'javascript', 'html', 'jquery', 'react', 'frontend', 'front end', 'philosophy'],
	"Joe Zeng": ['backend', 'back end', 'java', 'python', 'opencv', 'html', 'mysql', 'photoshop', 'go', 'grpc', 'protobuf', 'html', 'c', 'sql', 'ocaml', 'chinese'],
	"John Sloan": ['ios', 'apple sdk', 'mobile', 'mobile sdk', 'swift', 'objective c', 'ping pong'],
	"Jonathan Amazon": ['machine learning', 'french', 'spanish', 'c++', 'python', 'c', 'postgres', 'sql', 'go', 'grpc', 'cuda', 'opengl', 'aws', 'circuit design'],
	"Jonathan Yin": ['backend', 'back end'],
	"Josh Tepper": ['backend', 'back end', 'c++', 'java', 'sql', 'go', 'docker', 'kubernetes', 'javascript', 'mysql', 'unix', 'linux', 'c', 'bash', 'git', 'mathematica', 'shell scripting', 'postgres', 'hebrew', 'physics'],
	"Josh Goldenberg": ['product', 'sql', 'java', 'product strategy', 'machine learning', 'strategy', 'economics', 'philosophy'],
	"JJ Jiang": ['product', 'product strategy', 'gtm', 'product launch'],
	"JT Turner": ['research', 'java', 'python', 'machine learning', 'unix', 'linux', 'neural networks', 'cetf', 'baseball', 'football', 'hockey', 'deep learning', 'weightlifting', 'cats'],
	//"Justin Kuehn": ['aml', 'c#', 'java', 'javascript', 'python', 'c', 'visual studio', 'eclipse', 'react', 'sql', 'flux', 'go', 'xml', 'machine learning', 'computer vision', 'robotics', 'german', 'golfing', 'weightlifting'],
	"Karen Herder": ['dst', 'photography', 'labeling', 'homes.com'],
	"Keah Lonergan": ['arlo', 'skyline', 'enterprise', 'customer success', 'offerup', 'homes.com', 'wattpad', 'build.com', 'confluence', 'periscope', 'saas', 'running'],
	"Kevin Chen": ['accounting', 'loans', 'finance', 'excel', 'powerpoint', 'quickbooks', 'bookkeeping', 'snowboarding', 'hiking', 'weightlifting'],
	"Kevin Weiss": ['business development', 'strategy', 'strategic planning', 'scuba diving', 'mba', 'skiing', 'golfing', 'sales', 'marketing', 'oem', 'computer security', 'cloud computing'],
	"Kia Edwards": ['product marketing', 'marketing', 'running', 'dogs', 'wine', 'soca music', 'creative writing', 'public speaking', 'cold calling', 'gymnastics', 'writing', 'budgeting'],
	"Kris Rehberg": [],
	"Laura Caseley": ['dst', 'labeling', 'illustration', 'photoshop', 'illustrator', 'wordpress', 'cms', 'graphic design'],
	"Lambert Wixson": ['machine learning', 'c++', 'embedded systems', 'xml', 'c#', '.net', 'python', 'objective c', 'aml'],
	"Lisa Fletcher": ['legal'],
	"Lisa Liu": ['product', 'squash', 'cats'],
	"Luke Luo": ['backend', 'back end', 'java', 'python', 'c++', 'sql', 'c', 'linux', 'r', 'matlab', 'javascript', 'data analysis'],
	//"Marlene Blake": ['finance', 'accounting'],
	"Marshall Jones": ['design', 'ui', 'web design', 'javascript', 'react', 'illustrator', 'photoshop', 'wireframing', 'frontend', 'front end'],
	"Matthew Zeiler": ['machine learning', 'computer vision', 'c++', 'java', 'python', 'matlab', 'c', 'linux', 'docker', 'algorithms', 'neural networks', 'cnn', 'convolutional neural networks', 'deconvolutional neural networks', 'fundraising', 'emacs', 'basketball'],
	"Michael Acar": ['backend', 'statistics'],
	"Michael McGrann": ['sales', 'government', 'saas', 'cloud computing', 'enterprise software'],
	"Michael Noonan": ['financial modeling', 'valuation', 'finance', 'strategy'],
	"Michael Gormish": ['research', 'computer vision', 'machine learning', 'project management', 'python', 'linux', 'matlab', 'c++', 'embedded systems', 'c', 'patents', 'patenting', 'compression'],
	"Michael Tolbert": ['dst', 'italian', 'labeling', 'homes.com'],
	"Miguel Rodriguez": ['aml', 'machine learning', 'mathematics', 'statistics', 'python', 'postgres', 'java', 'sql', 'git', 'r', 'matlab', 'sage', 'bash', 'flask', 'airflow', 'presto', 'big data', 'data structures'],
	//"Mike Vaccarino": ['sales', 'social media', 'research', 'project management', 'strategy'],
	"Minh Tran": ['dst', 'python', 'scripting', 'labeling', 'illustration', 'web design', 'indesign', 'illustrator', 'photoshop', 'vietnamese', 'cats'],
	"Mohammad Afshar": ['python', 'machine learning', 'computer vision', 'redshift', 'algorithms', 'pytorch', 'tensorflow', 'java', 'hadoop', 'hbase', 'sql', 'latex', 'docker', 'scala', 'torch', 'aws', 'swift', 'postgres', 'opengl', 'deep learning', 'weightlifting'],
	"Monica Watson": ['social media', 'blog', 'blogging', 'marketing', 'social networking', 'flash', 'video editing', 'copy editing', 'photography', 'video', 'graphic design', 'email marketing', 'digital media', 'indesign', 'html', 'photoshop', 'wordpress'],
	//"Musa Almiggabber": ['marketing', 'social media', 'basketball', 'painting', 'music'],
	//"Nada Elkady": ['marketing', 'email marketing', 'lead generation', 'seo', 'sem', 'strategy', 'digital marketing', 'strategic planning', 'user experience'],
	"Natalie Fletcher": ['marketing', 'blog', 'blogging', 'content marketing', 'copy editing', 'creative writing'],
	"Peter Beck": ['music', 'guitar', 'songwriting', 'foot glides', 'beatboxing', 'saas', 'customer success', 'digital media', 'advertising', 'partnerships', 'strategy', 'marketing', 'social media', 'lead generation', 'new media', 'brand architecture', 'machine learning'],
	"Ravi Neppalli": ['sales', 'bitcoin', 'financial modeling', 'strategy', 'blockchain', 'excel', 'negotiation'],
	"Rigel Swavely": ['backend', 'back end', 'machine learning', 'java', 'python', 'algorithms', 'data structures', 'html', 'git', 'ruby', 'mysql', 'css', 'css', 'guitar', 'spanish'],
	"Robert Wen": ['infrastructure', 'linux', 'shell scripting', 'big data', 'machine learning', 'linux', 'red hat', 'unix', 'python', 'c', 'aws', 'hadoop', 'operating systems', 'azure', 'chinese', 'docker', 'cloud computing', 'virtualization'],
	"Robert Audroue": ['product design', 'design', 'graphic design', 'branding', 'photography', 'sketching', 'illustration', 'ui', 'ux', 'css', 'rhino', 'photoshop', 'illustrator', 'xhtml', 'solidworks', 'indesign', 'french'],
	"Robert Everson": ['linux', 'python', 'bash', 'tcp', 'dns', 'shell scripting', 'system administration', 'perl', 'ubuntu', 'administration', 'sawmill'],
	"Ron McNeely": ['cycling', 'sales', 'hiking', 'gardening', 'dutch', 'security', 'project management', 'cloud computing', 'voip', 'network security', 'virtualization', 'product management', 'saas', 'linux', 'sql', 'telecommunications', 'systems engineering'],
	"Rudi Chiarito": ['linux', 'distributed computing', 'machine learning', 'ssl', 'aws', 'datadog', 'kubernetes', 'infrastructure', 'running', 'italian'],
	"Samuel Dodge": ['research', 'machine learning', 'computer vision', 'opencv', 'matlab', 'deep learning'],
	"Scott Foster": ['arlo', 'skyline', 'cellebrite', 'six', 'travelers', 'project management', 'scratch', 'python', 'html', 'css', 'surfing', 'golfing', 'skiing'],
	"Sean Alger": ['sales', 'government', 'public sector', 'golfing'],
	"Sharon Junor": ['spreadsheets', 'customer service', 'powerpoint', 'social media', 'event planning', 'strategic planning'],
	"Skip Everling": ['technical writing', 'python', 'machine learning', 'data analysis', 'statistics', 'research', 'sql', 'aws', 'javascript', 'nlp', 'deep learning', 'cognitive science', 'developer relations', 'evangelist', 'hackathons', 'public speaking', 'writing', 'psychology'],
	"Sujit Poudel": ['mobile', 'mobile sdk', 'android', 'android sdk', 'shell scripting', 'php', 'python', 'c', 'mysql', 'html', 'javascript', 'sql', 'xml', 'git', 'css', 'linux', 'ajax', 'html', 'visual c++', 'c++', 'embedded c', 'physics', 'ping pong'],
	"Trevor Masters": ['mobile', 'mobile sdk', 'android', 'android sdk', 'c++', 'java', 'kotlin', 'c', 'matlab', 'r', 'sql', 'python', 'objective c', 'c#', 'android studio', 'groovy', 'martial arts', 'taekwondo'],
	"Tricia Marshall": ['hr', 'onboarding', 'recruiting', 'human resources', 'benefits', 'employee benefits', 'orientation', 'interviews', 'interviewing'],
	//"Ulas Bardak": ['machine learning', 'algorithms', 'distributed systems', 'web development', 'data mining', 'analytics', 'big data', 'cloud computing', 'python', 'php', 'c++', '.net', 'hadoop', 'c#', 'git', 'sql', 'nlp', 'elasticsearch', 'turkish', 'japanese', 'thai', 'football'],
	"Vanessa Sorensen": ['marketing', 'social media', 'email marketing', 'blogging', 'blog', 'content management', 'digital marketing', 'seo', 'salesforce', 'final cut pro', 'video editing', 'lead generation', 'digital media', 'cats'],
	"Veracelle Vega": ['recruiting', 'talent management', 'hr', 'human resources', 'people', 'onboarding', 'hiring'],
	"Viktor Onyshchenko": ['russian', 'ukrainian', 'backend', 'back end', 'python', 'ruby', 'ruby on rails', 'web development', 'machine learning', 'javascript', 'html', 'git', 'pandas', 'node', 'css', 'linux', 'photoshop', 'c#', 'go', 'numpy'],
	"Wen Wang": ['cats', 'data analytics', 'chinese'],
	"Wesley Mann": ['data analysis', 'cetf', 'sql', 'postgres', 'redshift', 'c++', 'matlab', 'r', 'python', 'business operations', 'periscope', 'chess', 'basketball'],
	"Will Frey": ['machine learning', 'cloud computing', 'latex', 'c', 'linux', 'python', 'matlab', 'c++', 'lua', 'torch', 'deep learning', 'linear algebra'],
	"Xinli Jia": ['backend', 'back end', 'ios', 'python', 'java', 'c++', 'algorithms', 'machine learning', 'data structures', 'cloud computing', 'c', 'linux', 'django', 'hadoop', 'html', 'node', 'css', 'latex', 'tensorflow', 'aws', 'lambda', 'postgres', 'matlab', 'sql', 'react', 'javascript', 'mysql', 'unix', 'git', 'azure', 'chinese'],
	"Yanan Jian": ['research', 'big data', 'python', 'java', 'distributed systems', 'algorithms', 'machine learning', 'data mining', 'c', 'mongodb', 'django', 'linux', 'c++', 'html', 'android', 'nginx'],
	"Yang Sheng": ['backend', 'back end', 'openstack', 'python', 'go', 'chinese', 'linux', 'python', 'virtualization', 'tcp', 'sql', 'c++', 'html', 'css', 'centos', 'ubuntu', 'java', 'c', 'mysql', 'postgres', 'red hat'],
	"Yvette Zhang": ['python', 'chinese', 'javascript', 'aws', 'algorithms', 'data structures', 'postgres', 'redux', 'react', 'react native', 'css', 'lambda', 'node', 'sql', 'html', 'r', 'graphql', 'autocad'],
	"Yuncheng Dong": ['dst', 'photography', 'graphic design', 'photoshop', 'illustrator', 'fashion', 'labeling', 'chinese', 'digital photography'],
	"Zac Cortez": ['sales', 'cloud computing', 'saas', 'crm', 'salesforce', 'business development', 'surfing', 'basketball']
}

var mentorTags = {
	//"Abe Danziger": [],
	//"Adam Balint": [],
	"Alex Cook": ['eating', 'basketball', 'clarifai'],
	"Alex Freska": ['javascript', 'redux', 'jenkins'],
	//"Alison Klein": [],
	//"Amanda Coyle": [],
	//"Amy Kim": [],
	"Arya Seghatoleslami": ['javascript', 'react', 'redux'],
	//"Blossom Coryat": [],
	//"Brandon Clifton": [],
	//"Brian Novie": [],
	//"Briana Gangi": [],
	//"Chenchao Zhao": [],
	//"Chris Moore": [],
	//"Chul Gwon": [],
	//"Claire Geist": [],
	//"Dalmo Cirne": [],
	"Daniel Owsley": ['kubernetes', 'docker', 'bash'],
	//"David Eigen": [],
	"David Leonard": ['javascript'],
	//"David Kane": [],
	//"Dena Barnes": [],
	//"Dianna Barry": [],
	//"Edwin Renard": [],
	//"Eric Loh": [],
	//"Elon Daniel": [],
	//"Eran Nussinovitch": [],
	//"Eugenie Ma": [],
	//"Glen You": [],
	"Grant Lightner": ['woodworking', 'cars', 'car repair', 'auto repair', 'handymanning'],
	//"Habib Talavati": [],
	"Haicheng Lin": ['graphic design', '3d animation', '3d modeling', 'data visualization', 'animation'],
	"Harmit Minhas": ['python', 'go', 'weightlifting'],
	//"Herbert Zheng": [],
	//"Janvier Wijaya": [],
	"Jared Lerner": ['photoshop','python', 'sql'],
	//"Jason Culler": [],
	//"Jecky Tian": [],
	//"Jeff Zhang": [],
	//"Jesse Rappaport": [],
	//"Joe Zeng": [],
	//"John Sloan": [],
	//"Jonathan Amazon": [],
	//"Jonathan Yin": [],
	"Josh Tepper": ['go', 'docker', 'kubernetes'],
	//"Josh Goldenberg": [],
	//"JJ Jiang": [],
	"JT Turner": ['deep learning', 'python', 'baseball'],
	//"Justin Kuehn": [],
	//"Karen Herder": [],
	//"Keah Lonergan": [],
	//"Kevin Weiss": [],
	//"Kia Edwards": [],
	//"Laura Caseley": [],
	//"Lambert Wixson": [],
	//"Lisa Fletcher": [],
	//"Lisa Liu": [],
	//"Luke Luo": [],
	//"Marshall Jones": [],
	"Matthew Zeiler": ['fundraising', 'cnn', 'convolutional neural networks', 'neural networks', 'machine learning', 'emacs', 'deconvolutional neural networks'],
	//"Michael Acar": [],
	//"Michael McGrann": [],
	//"Michael Noonan": [],
	"Michael Gormish": ['patents', 'computer vision', 'compression'],
	//"Michael Tolbert": [],
	//"Miguel Rodriguez": [],
	//"Minh Tran": [],
	//"Mohammad Afshar": [],
	//"Monica Watson": [],
	//"Musa Almiggabber": [],
	//"Natalie Fletcher": [],
	"Peter Beck": ['guitar', 'songwriting', 'foot glides', 'beatboxing'],
	"Ravi Neppalli": ['sales', 'negotiation', 'excel'],
	"Rigel Swavely": ['machine learning', 'python', 'guitar'],
	//"Robert Wen": [],
	//"Robert Audroue": [],
	//"Robert Everson": [],
	//"Rudi Chiarito": [],
	//"Samuel Dodge": [],
	//"Scott Foster": [],
	//"Sean Alger": [],
	//"Sharon Junor": [],
	"Skip Everling": ['public speaking', 'writing', 'psychology', 'technical writing'],
	//"Sujit Poudel": [],
	//"Trevor Masters": [],
	//"Tricia Marshall": [],
	//"Vanessa Sorensen": [],
	//"Veracelle Vega": [],
	//"Viktor Onyshchenko": [],
	//"Wesley Mann": [],
	//"Will Frey": [],
	//"Xinli Jia": [],
	//"Yanan Jian": [],
	//"Yang Sheng": [],
	//"Yvette Zhang": [],
	"Yuncheng Dong": ['photoshop','digital photography', 'photography', 'chinese'],
	//"Zac Cortez": []
}

var employeeTitles = {
	"Abe Danziger": "VP of Customer Success",
	"Alex Cook": "Sales Development Representative",
	"Alex Freska": "Senior Frontend Engineer",
	"Alison Klein": "General Counsel",
	"Amanda Coyle": "Human Resources Business Partner",
	"Amy Kim": "Senior Product Lead",
	"Arya Seghatoleslami": "Senior Frontend Engineer",
	"Billy Lawler": "Senior Infrastructure Engineer",
	"Blossom Coryat": "Senior Sales Engineer",
	"Brian Novie": "Senior iOS Engineer",
	"Briana Gangi": "IT Support Specialist",
	"Chenchao Zhao": "Senior Research Scientist",
	"Chris Moore": "Director of Finance and Operations",
	"Chul Gwon": "Staff Research Scientist",
	"Claire Geist": "Data Strategist Manager",
	"Dalmo Cirne": "Director of Mobile Engineering",
	"Daniel Owsley": "Infrastructure Engineer",
	"David Eigen": "Senior Staff Research Scientist",
	"David Leonard": "Frontend Engineer",
	"David Kane": "Sales Development Representative",
	"Dena Barnes": "Enterprise Account Executive",
	"Dianna Barry": "Backend Engineer",
	"Edwin Renard": "Lead Talent Partner",
	"Elon Daniel": "Office Manager",
	"Eran Nussinovitch": "AML Engineer",
	"Eric Loh": "Backend Intern",
	"Eugenie Ma": "Talent Acquisition Associate",
	"Glen You": "Senior Account Executive - Public Sector",
	"Grant Lightner": "Technical Program Manager",
	"Habib Talavati": "Machine Learning Architect",
	"Haicheng Lin": "Marketing Designer",
	"Harmit Minhas": "Backend Intern",
	"Herbert Zheng": "Head of Backend",
	"Janvier Wijaya": "Backend Engineer",
	"Jared Lerner": "Support Engineering Lead",
	"Jason Culler": "Design Lead",
	"Jecky Tian": "Backend Engineer",
	"Jesse Rappaport": "Frontend Engineer",
	"Joe Zeng": "Backend Engineer",
	"John Sloan": "iOS Engineer",
	"Jonathan Amazon": "Senior ML Engineer",
	"Jonathan Yin": "Backend Intern",
	"Josh Tepper": "Staff Backend Engineer",
	"Josh Goldenberg": "Lead Product Manager",
	"JJ Jiang": "Director of Product",
	"JT Turner": "Senior Research Scientist",
	"Karen Herder": "Project Manager",
	"Keah Lonergan": "Client Success Manager",
	"Kevin Chen": "Accountant",
	"Kevin Weiss": "VP Business Development",
	"Kia Edwards": "Product Marketing Associate",
	"Kris Rehberg": "Senior Infrastructure Engineer",
	"Laura Caseley": "Data Labeler",
	"Lambert Wixson": "Head of AML",
	"Lisa Fletcher": "Assistant General Counsel",
	"Lisa Liu": "Product Manager",
	"Luke Luo": "Backend Engineer",
	"Marshall Jones": "Director of UX",
	"Matthew Zeiler": "Founder & CEO",
	"Michael Acar": "Senior Backend Engineer",
	"Michael McGrann": "Senior Account Executive - Public Sector",
	"Michael Noonan": "Chief of Staff",
	"Michael Gormish": "Staff Research Scientist",
	"Michael Tolbert": "Senior Data Strategist",
	"Miguel Rodriguez": "Applied Machine Learning Engineer",
	"Minh Tran": "Senior Technical Data Strategist",
	"Mohammad Afshar": "AML Engineer",
	"Monica Watson": "Content Marketing Manager",
	"Musa Almiggabber": "Social Media Intern",
	"Natalie Fletcher": "Content Marketing Editor",
	"Peter Beck": "Senior Customer Success Manager",
	"Ravi Neppalli": "Sales Development Representative",
	"Rigel Swavely": "Senior Machine Learning Engineer",
	"Robert Audroue": "Product Designer",
	"Robert Everson": "Staff Site Reliability Engineer",
	"Robert Wen": "Interim VP of Engineering",
	"Ron McNeely": "Senior Sales Engineer",
	"Rudi Chiarito": "Senior Staff Infrastructure Engineer",
	"Samuel Dodge": "Senior Research Scientist, Deep Learning",
	"Scott Foster": "Lead Technical Program Manager",
	"Sean Alger": "General Manager, Public Sector",
	"Sharon Junor": "Executive Assistant to the CEO",
	"Skip Everling": "Senior Developer Evangelist",
	"Sujit Poudel": "Senior Android Engineer",
	"Trevor Masters": "Senior Android Engineer",
	"Tricia Marshall": "Head of People",
	"Vanessa Sorensen": "Product Marketing Manager",
	"Veracelle Vega": "Vice President, People + Culture",
	"Viktor Onyshchenko": "Senior Backend Engineer",
	"Wen Wang": "Data Analytics Intern",
	"Wesley Mann": "Data Analytics Optimization",
	"Will Frey": "Senior AML Engineer",
	"Xinli Jia": "Backend Engineer",
	"Yanan Jian": "Research Scientist",
	"Yang Sheng": "Backend Engineer",
	"Yuncheng Dong": "Data Labeler",
	"Yvette Zhang": "Backend Engineer",
	"Zac Cortez": "Senior Account Executive"
}

var employeeSlackIDs = {
	"Abe Danziger": "UDMABUR5Z",
	"Alex Cook": "UDFFL0S4F",
	"Alex Freska": "UCV6PQWNR",
	"Alison Klein": "UCPLTTC3S",
	"Amanda Coyle": "UCPLW96AU",
	"Amy Kim": "U38R73NFL",
	"Arya Seghatoleslami": "UCB69GRUZ",
	"Billy Lawler": "",
	"Blossom Coryat": "UF845JHN0",
	"Brian Novie": "U8M240AJX",
	"Briana Gangi": "UC6JQCDD3",
	"Chenchao Zhao": "UJ9BLK36H",
	"Chris Moore": "UB14KP75Z",
	"Chul Gwon": "UCF4LDGC8",
	"Claire Geist": "U3NQ09HA6",
	"Dalmo Cirne": "U4R4U2RMG",
	"Daniel Owsley": "UD4D2R0Q4",
	"David Eigen": "U0688V119",
	"David Leonard": "U9ETYV50S",
	"David Kane": "UC4QUCE1L",
	"Dena Barnes": "U8ABC3K9V",
	"Dianna Barry": "UCLTGGBV0",
	"Edwin Renard": "UF8F0HZ6Z",
	"Elon Daniel": "UAR0VRRU6",
	"Eran Nussinovitch": "UE7443WMS",
	"Eric Loh": "UC7LRRJ2X",
	"Eugenie Ma": "U9TQV3N49",
	"Glen You": "UFS6V415L", 
	"Grant Lightner": "UCD35905U",
	"Habib Talavati": "U210M97RN",
	"Haicheng Lin": "UG609MKAT",
	"Harmit Minhas": "UBHHQDJM8",
	"Herbert Zheng": "UA8D6LM3Q",
	"Janvier Wijaya": "UCD2NH678",
	"Jared Lerner": "U0HM03678",
	"Jason Culler": "U0HLQ2XBR",
	"Jecky Tian": "UBSAF6W87",
	"Jesse Rappaport": "UAUFFD57H",
	"Joe Zeng": "UDMK1PQFP",
	"John Sloan": "U1JLFLA59",
	"Jonathan Amazon": "U9CF9DSD9",
	"Jonathan Yin": "UBGRC2SRE",
	"Josh Tepper": "U1NPGME9Y",
	"Josh Goldenberg": "U9NCHNRRQ",
	"JJ Jiang": "UFR8D7RFF",
	"JT Turner": "UCB3NH87J", 
	"Karen Herder": "U3P3H83K6",
	"Keah Lonergan": "UA8D6BP7Y",
	"Kevin Chen": "UHWH0CED6",
	"Kevin Weiss": "UBFRGDZL5",
	"Kia Edwards": "UGWA77NDU",
	"Kris Rehberg": "",
	"Laura Caseley": "UF8D44761",
	"Lambert Wixson": "U9ST0KMN0",
	"Lisa Fletcher": "U8DTA54SJ",
	"Lisa Liu": "UDVEQ2U2V",
	"Luke Luo": "UC4GQ4GHM",
	"Marshall Jones": "U0BE2G7FH",
	"Matthew Zeiler": "U0684GKHU",
	"Michael Acar": "UFK7WGT4Y",
	"Michael McGrann": "UFYTCRFPY",
	"Michael Noonan": "UE5JC4P28",
	"Michael Gormish": "UB52JKTU1",
	"Michael Tolbert": "U3MHAGXNC",
	"Miguel Rodriguez": "UCQBJS692",
	"Minh Tran": "U3P16RFTL",
	"Mohammad Afshar": "UCLP63GJY",
	"Monica Watson": "UC38T4MQC",
	"Musa Almiggabber": "UDZHEAD1U",
	"Natalie Fletcher": "U5VRS7UQ2",
	"Peter Beck": "UEPHEM0NM",
	"Ravi Neppalli": "UB9DTKLEN",
	"Rigel Swavely": "U4V7ARRB4",
	"Robert Wen": "U0688TC4U", 
	"Robert Audroue": "UDCHUUT7G",
	"Robert Everson": "U6QT3V7HP",
	"Ron McNeely": "UJ52RK6NA",
	"Rudi Chiarito": "U0B2HLYBD",
	"Samuel Dodge": "UB2D80HM5",
	"Scott Foster": "UB68GG3L6",
	"Sean Alger": "UB0LXC7UH",
	"Sharon Junor": "UALCWF1KQ",
	"Skip Everling": "UC24A85TR",
	"Sujit Poudel": "U86M0NBHB",
	"Trevor Masters": "U8WF3DFDH",
	"Tricia Marshall": "U5055036Z",
	"Vanessa Sorensen": "UBAF9C9AT",
	"Veracelle Vega": "UB9DTLUE6",
	"Viktor Onyshchenko": "UDS6CRR5L",
	"Wen Wang": "UH8T2JCKB",
	"Wesley Mann": "UA8GZB5MM",
	"Will Frey": "UDFFKLDEK",
	"Xinli Jia": "UDEDZ84E6",
	"Yanan Jian": "U5VE766KB",
	"Yang Sheng": "UDFFL39P1",
	"Yuncheng Dong": "UF7EYB9KJ",
	"Yvette Zhang": "UCRRSB0AY",
	"Zac Cortez": "U7PCLJB2A"
}